project 'Funky.xcodeproj'

target 'iOS-Example' do
  use_frameworks!
  pod 'FunkyObjC', :path => '../'

  target 'Tests' do
    inherit! :search_paths
    pod 'OCMock'
  end
  
  target 'IntegrationTests' do
    inherit! :search_paths
  end
end

target 'macOS-Example' do
  use_frameworks!
  pod 'FunkyObjC', :path => '../'
end

target 'tvOS-Example' do
  use_frameworks!
  pod 'FunkyObjC', :path => '../'
end

target 'watchOS-Example' do
  use_frameworks!
  pod 'FunkyObjC', :path => '../'
end
