project 'Funky.xcodeproj'

target 'Funky_Example' do
  use_frameworks!
  pod 'FunkyObjC', :path => '../'

  target 'Funky_Tests' do
    inherit! :search_paths
    pod 'OCMock'
    pod 'Specta'
    pod 'Expecta'
  end
end
